apiVersion: v1
kind: ConfigMap
metadata:
  name: mijnkia-ini
data:
  MijnKia.ini: |-
    [MijnKia]
    loginEmail=ralph.smeets@gmail.com
    LoginPassword=VFzT0fnz@kia

    [Influx]
    InfluxDBServer=
    InfluxDB=

    [ABetterRoutePlanner]
    #Login to ABRP website, setup live data, choose Torque Pro and find the field with the email ID, looks like: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    abrp_token=c2abeaf2-aa2b-4000-a069-a65a5a07bbb0
    car_model=kia:niro:19:64:other
    #To provide the location of the car to ABRP specify YES below. Better to override it in the app and use your phone's location which updates far more frequently
    ProvideLocationToABRP=NO
    #Register an account on OpenWeatherMap and get API Key
    OpenWeatherMapAPIKey=
