pipeline {
    agent {  label "kubagent" }

    stages {
        stage('Build') {
            steps {
                echo 'Building this thing!'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}