pipeline {
    agent {  label "python-kubagent" }

    stages {
        stage('Build') {
                steps {
                    sh '''
                    /kaniko/executer --context `pwd` --destination ralphseets/mijnkia-test:0.1
                '''
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}